src/Entity/Ali.php
<?php

/*
 * Eclipse Wiki
 */

namespace App\Entity;

use App\Attribute\Icon;

/**
 * Ali is an artificial limited intelligence
 */
#[Icon('ali')]
class Ali extends Character
{

    public function getDescription(): string
    {
        return 'IAL';
    }

}

src/Entity/Fighter.php
<?php

/*
 * eclipse-wiki
 */

namespace App\Entity;

/**
 * This is a generic fighter
 */
interface Fighter
{

    public function getToughness(): int;

    public function getTotalArmor(): int;

    public function getParry(): int;

    public function getTitle(): string;

    public function isWildcard(): bool;

    public function getMalusAgainstRangedAttack(): int;

    public function getTokenPicture(): ?string;

}

src/Form/Npc.php
<?php

/*
 * Eclipse Wiki
 */

namespace App\Form;

use App\Entity\Character;
use App\Repository\BackgroundProvider;
use App\Repository\FactionProvider;
use App\Repository\MorphProvider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Description of Npc
 */
class Npc extends AbstractType
{

    protected $background;
    protected $faction;
    protected $morph;

    public function __construct(BackgroundProvider $bg, FactionProvider $fac, MorphProvider $morph)
    {
        $this->background = $bg;
        $this->faction = $fac;
        $this->morph = $morph;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('background', Type\ProviderChoiceType::class, ['provider' => $this->background, 'placeholder' => '--- Choisissez un Historique ---'])
                ->add('faction', Type\ProviderChoiceType::class, ['provider' => $this->faction, 'placeholder' => '--- Choisissez une Faction ---'])
                ->add('morph', Type\ProviderChoiceType::class, ['provider' => $this->morph, 'placeholder' => '--- Choisissez un Morphe ---'])
                ->add('generate', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('data_class', Character::class);
        $resolver->setDefault('empty_data', function (FormInterface $form) {
            $bg = $form->get('background')->getData();
            $fac = $form->get('faction')->getData();

            if (!is_null($bg) && !is_null($fac)) {
                return new Character($bg, $fac);
            }

            return null;
        });
    }

}

templates/npc/actions.html.twig
<a href="{{ path('app_vertexcrud_show', {pk: npc.pk}) }}" title="Voir"><i class="icon-eye"></i></a>
<a href="{{ path('app_npcgenerator_edit', {pk: npc.pk}) }}" title="Modifier"><i class="icon-d6"></i></a>
    {% if npc.category == 'transhuman' %}
    <a href="{{ path('app_npcgenerator_info', {pk: npc.pk}) }}" title="Informations"><i class="icon-edit"></i></a>
    {% else %}
    <a href="{{ path('app_vertexcrud_edit', {pk: npc.pk}) }}" title="Informations"><i class="icon-edit"></i></a>
    {% endif %}
<a href="{{ path('app_profilepicture_token', {pk: npc.pk}) }}" title="Créer un token"><i class="icon-user-circle"></i></a>
<a href="{{ path('app_npcgenerator_gear', {pk: npc.pk}) }}" title="Matériel"><i class="icon-wrench"></i></a>
<a href="{{ path('app_npcgenerator_battle', {pk: npc.pk}) }}" title="Combat"><i class="icon-gun"></i></a>
    {% if npc.category == 'transhuman' and npc.npcTemplate %}
    <a href="{{ path('app_profilepicture_template', {pk: npc.pk}) }}" title="Générer un profil réseau"><i class="icon-profile"></i></a>
    {% endif %}
    {% if npc.category != 'freeform' %}
    <a href="{{ path('app_npcgenerator_sleeve', {pk: npc.pk}) }}" title="Resleeving"><i class="icon-sleeve"></i></a>
    {% endif %}
<a href="{{ path('app_npcgenerator_duplicate', {pk: npc.pk}) }}" title="Dupliquer"><i class="icon-duplicate"></i></a>
    {% if npc.category == 'transhuman' and npc.instantiatedFrom %}
    <a href="{{ path('app_npcgenerator_resync', {pk: npc.pk}) }}" title="Resynchroniser avec le parent"><i class="icon-spin3"></i></a>
    {% endif %}   
    {% if not npc.wildcard %}
    <a href="{{ path('app_npcgenerator_pushpdf', {pk: npc.pk}) }}" title="Envoyer la fiche de perso"><i class="icon-push"></i></a>
    {% endif %}   
<a href="{{ path('app_vertexcrud_rename', {pk: npc.pk}) }}" title="Renommer"><i class="icon-rename"></i></a>
<a href="{{ path('app_vertexcrud_archive', {pk: npc.pk}) }}" title="He's dead, Jim"><i class="icon-dead"></i></a>
<a href="{{ path('app_vertexcrud_delete', {pk: npc.pk}) }}" title="Effacer"><i class="icon-trash-empty"></i></a>

templates/npc/battle.html.twig
{% extends "base.html.twig" %}
{% form_theme form _self %}

{% block header_title %}
    {{ include('npc/menu.html.twig', {npc: form.vars.data}) }}
{% endblock %}

{% block _npc_attacks_attacks_widget %}
    <div id="{{ form.vars.id }}" class="collection">
        <template x-for="(attack, idx) in attacks">

            <div class="pure-g">
                <div class="pure-u-1-2">
                    {{ form_widget(form.vars.prototype.title, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][title]'",
                            'x-model': "attack.title",
                            'class': 'pure-input-1 highlight',
                            placeholder: 'Titre de l\'attaque'
                        } 
                    }) }}
                </div>
                <div class="pure-u-1-4">
                    {{ form_widget(form.vars.prototype.reach, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][reach]'",
                            'x-model': "attack.reach"
                        } 
                    }) }}
                </div>
                <nav class="pure-u-1-4">
                    <a x-on:click="removeAttack(idx)"><i class="icon-trash-empty"></i></a>
                </nav>
                <div class="pure-u-1-1">
                    {{ form_widget(form.vars.prototype.rateOfFire, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][rateOfFire]'",
                            'x-model': "attack.rateOfFire"
                        } 
                    }) }}
                    ×
                    <label x-text="attack.roll.name"></label>
                    {{ form_widget(form.vars.prototype.roll.name, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][roll][name]'",
                            'x-model': "attack.roll.name"
                        } 
                    }) }}
                    {{ form_widget(form.vars.prototype.roll.roll, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][roll][roll]'",
                            'x-bind:value': "attack.roll.dice + attack.roll.modifier"
                        } 
                    }) }}     
                    +
                    {{ form_widget(form.vars.prototype.rollBonus, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][rollBonus]'",
                            'x-model': "attack.rollBonus"
                        } 
                    }) }}                    
                </div>
                <div class="pure-u-1-1">
                    {{ form_widget(form.vars.prototype.damage, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][damage]'",
                            'x-bind:value': "damageToString(attack.damage)"
                        } 
                    }) }}
                    PA
                    {{ form_widget(form.vars.prototype.armorPiercing, {
                        attr: {
                            'x-bind:name': "'npc_attacks[attacks][' + idx + '][armorPiercing]'",
                            'x-model': "attack.armorPiercing"
                        } 
                    }) }}
                </div>
            </div>
        </template>
    </div>
{% endblock %}

{% block _npc_attacks_armors_widget %}
    <div id="{{ form.vars.id }}" class="collection">
        <template x-for="(armor, idx) in armors">

            <div class="pure-g">
                <div class="pure-u-3-4">
                    {{ form_widget(form.vars.prototype.name, {
                        attr: {
                            'x-bind:name': "'npc_attacks[armors][' + idx + '][name]'",
                            'x-model': "armor.name",
                            'class': 'pure-input-1 highlight',
                            placeholder: 'Nom de l\'armure'
                        } 
                    }) }}
                </div>
                <nav class="pure-u-1-4">
                    <a x-on:click="removeArmor(idx)"><i class="icon-trash-empty"></i></a>
                </nav>
                <div class="pure-u-1-3">
                    {{ form_widget(form.vars.prototype.protect, {
                        attr: {
                            'x-bind:name': "'npc_attacks[armors][' + idx + '][protect]'",
                            'x-model': "armor.protect",
                            placeholder: 'Protection'
                        } 
                    }) }}
                </div>
                <div class="pure-u-1-3">
                    {{ form_widget(form.vars.prototype.special, {
                        attr: {
                            'x-bind:name': "'npc_attacks[armors][' + idx + '][special]'",
                            'x-model': "armor.special",
                            'placeholder': 'Spécial'
                        } 
                    }) }}
                </div>  
                <div class="pure-u-1-3">
                    {{ form_widget(form.vars.prototype.zone, {
                        attr: {
                            'x-bind:name': "'npc_attacks[armors][' + idx + '][zone]'",
                            'x-model': "armor.zone",
                            placeholder: 'Zone'
                        } 
                    }) }}
                </div>
            </div>
        </template>
    </div>
{% endblock %}


{% block content %}
    <div x-data="{{ form.vars.data|json_encode()|escape('html_attr') }}">
        {{ form(form, {attr: {'x-data': 'behavior'}}) }}
    </div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script type="module">
        Alpine.data('behavior', () => ({
                getSkill(name) {
                    for (let idx = 0; idx < this.skills.length; idx++) {
                        let skill = this.skills[idx]
                        if (skill.name === name) {
                            return skill
                        }
                    }

                    return {dice: 4, modifier: -2}
                },
                getSaWoAttribute(name) {
                    for (let idx = 0; idx < this.attributes.length; idx++) {
                        let attr = this.attributes[idx]
                        if (attr.name === name) {
                            return attr
                        }
                    }
                },
                damageToString(damage) {
                    let str = []
                    Object.keys(damage.diceCount).forEach(function (key, index) {
                        let val = damage.diceCount[key]
                        if (val > 0) {
                            str.push(val + 'd' + key)
                        }
                    })
                    if (damage.bonus > 0) {
                        str.push(damage.bonus)
                    }

                    return str.join('+')
                },
                addMeleeWeapon(ev) {
                    let weapon = JSON.parse(ev.target.value)
                    let dmg = weapon.damage
                    let strength = this.getSaWoAttribute('Force')
                    dmg.diceCount[strength.dice]++
                    let fighting = this.getSkill("Combat")

                    this.attacks.push({
                        title: weapon.name,
                        roll: {
                            name: "Combat",
                            dice: fighting.dice,
                            modifier: fighting.modifier
                        },
                        armorPiercing: weapon.ap,
                        reach: 'Mêlée',
                        rollBonus: 0,
                        rateOfFire: 1,
                        damage: dmg
                    })

                    ev.target.value = ""

                },
                addRangedWeapon(ev) {
                    let weapon = JSON.parse(ev.target.value)
                    let shooting = this.getSkill("Tir")

                    this.attacks.push({
                        title: weapon.name,
                        roll: {
                            name: "Tir",
                            dice: shooting.dice,
                            modifier: shooting.modifier
                        },
                        armorPiercing: weapon.ap,
                        reach: weapon.reach,
                        rollBonus: 0,
                        rateOfFire: weapon.rof,
                        damage: weapon.damage
                    })

                    ev.target.value = ""

                },
                removeAttack(k) {
                    this.attacks.splice(k, 1)
                },
                addArmor(ev) {
                    let armor = JSON.parse(ev.target.value)
                    this.armors.push(armor)
                    ev.target.value = ""
                },
                removeArmor(k) {
                    this.armors.splice(k, 1)
                }
            }))
    </script>
{% endblock %}

templates/npc/character_sheet.pdf.twig
{# PDF Summary of Character Sheet #}
{% extends "base.pdf.twig" %}

{% macro print_trait(trait, rof = 1, bonus = 0) %}
    d{{ trait.dice }}
    {% set delta = trait.modifier + bonus %}
    {% if delta > 0 %}
        + {{ delta }}
    {% endif %}
    {% if delta < 0 %}
        - {{ -delta }}
    {% endif %}
{% endmacro %}

{% block content %}
    <div class="character-show">
        <div class="pure-g">
            <div class="pure-u-1-2">
                <h2>Attributs</h2>
                <table class="pure-table">
                    {% for attr in vertex.attributeRolls %}
                        <tr>
                            <td>{{ attr.label }}</td>
                            <td>{{ _self.print_trait(attr) }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <h2>Carac. 2<sup>ndaires</sup></h2>
                <table class="pure-table">
                    <tr>
                        <td>Parade</td>
                        <td>{{ vertex.parry }}</td>
                    </tr>
                    <tr>
                        <td>Malus distance</td>
                        <td>{{ vertex.rangedMalus }}</td>
                    </tr>
                    <tr>
                        <td>Résistance</td>
                        <td>{{ vertex.toughness }} ({{ vertex.totalArmor }})</td>
                    </tr>
                    <tr>
                        <td>Sécurité</td>
                        <td>{{ vertex.security }}</td>
                    </tr>
                </table>
            </div>      
            <div class="pure-u-1-2">
                <h2>Compétences</h2>
                <table class="pure-table">
                    {% for skill in vertex.skillRolls %}
                        <tr>
                            <td>{{ skill.label }}</td>
                            <td>{{ _self.print_trait(skill) }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>   
            <div class="pure-u-1">
                <ul class="edge-list">
                    {% for edge in vertex.edges %}
                        <li>{{ edge.name }}
                        </li>
                    {% endfor %}
                    {% for edge in vertex.morph.edges %}
                        <li>{{ edge.name }}
                        </li>
                    {% endfor %}
                </ul>
            </div>  
            <div class="pure-u-1">
                <table class="pure-table">
                    {% for item in vertex.attackRolls %}
                        <tr>
                            <td>{{ item.title }}</td>
                            <td>{{ item.reach }}</td>
                            <td>{{ item.rateOfFire }}×</td>
                            <td>{{ item.roll.label }}</td>
                            <td>{{ _self.print_trait(item.roll, item.rateOfFire, item.rollBonus) }}</td>
                            <td>{{ item.damage }}</td>
                            <td>PA {{ item.armorPiercing }}</td>                            
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}  

{% block stylesheets %}
    {{ parent() }}
    <style>
        h2:has(+ table) {
            margin-bottom: 0;
            font-size: 110%;
        }
        .edge-list {
            padding-left: 0;
        }
        .edge-list li {
            display: inline-block;
            margin-right: 1em;
        }
    </style>
{% endblock %}

templates/npc/edit_info.html.twig
{% extends "form.html.twig" %}
{% form_theme form _self %}

{% block title %}{{ form.vars.data.title }}{% endblock %}

{% block header_title %}
    {{ include('npc/menu.html.twig', {npc: form.vars.data}) }}
{% endblock %}

{% block _npc_info_content_label %}
    {{ form_label(form) }}
    {% include 'fragment/form_minitoolbar.html.twig' %}
    {% set vertex = form.parent.vars.data %}
    <div class="minitoolbar" x-data="npcToolbar('{{ form.vars.id }}')">
        <a href="{{ path('app_ollama_contentgenerate', {pk: vertex.pk, promptKey: 'npc-bg', prefill: {title: vertex.title|split(' ', 2)[0]}}) }}"
           class="pure-button button-delete" title="Cancel edition and append a LLM-generated background">
            <i class="icon-background"></i>
        </a>
        <a href="#" class="pure-button" title="Insert a known locations template" x-on:click.prevent="insertLocationTemplate">
            <i class="icon-location"></i>
        </a>
    </div>
    <script type="module">
        Alpine.data('npcToolbar', (widgetId) => ({
                insertLocationTemplate() {
                    const widget = document.getElementById(widgetId)
                    let selection = widget.value.substring(widget.selectionStart, widget.selectionEnd).trim().split("\n")
                    widget.value = widget.value.substring(0, widget.selectionStart)
                            + "{{ '{{location|habitat=|work=|fun=}}' }}\n"
                            + widget.value.substr(widget.selectionStart)
                }
            }))
    </script>
{% endblock %}

templates/npc/form_info.html.twig
{% extends "form.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    {{ include('fragment/init_autocomplete.html.twig', {element_id:'npc_info_content'}) }}
    <script>
        document.getElementById('npc_info_content').focus()
    </script>
{% endblock %}

{% block header_title %}
    {{ include('npc/menu.html.twig', {npc: form.vars.data}) }}
{% endblock %}

templates/npc/menu.html.twig
{# the header menu with title #}
<div style="float: right">
    {{ include('npc/actions.html.twig') }}
</div>
PNJ : {{ npc.title }} <i class="{{ vertex_icon(npc) }}"></i>

templates/npc/row.html.twig
<div class="pure-g">
    <div class="pure-u-1-4 pure-u-xl-1-12 thumb">
        <i class="{{ vertex_icon(item) }} {% if item.archived %}archived{% endif %}"></i>
    </div>
    <div class="pure-u-3-4 pure-u-xl-1-2">
        <a href="{{ path('app_vertexcrud_show', {pk: item.pk}) }}" class="block-link">
            <h2>{{ item.title }}</h2>
            <span>{{ item.description }}. Morphe: {{ item.morph.title }} ({{ item.powerIndex }})</span>
        </a>
    </div>
    <div class="pure-u-1 pure-u-xl-5-12">
        <nav class="listing-action">
            {{ include('npc/actions.html.twig', {npc:item}) }}
        </nav>
    </div>
</div>

templates/npc/show.html.twig
{% extends "vertex/show.html.twig" %}
{% set npc = vertex %}
{% macro print_trait(trait, rof = 1, bonus = 0) %}
    <button x-on:click="$dispatch('roll', { dice: {{ trait.dice }}, modifier: {{ trait.modifier + bonus }}, rof: {{ rof }} })"
            class="pure-button {{ trait.altered ? 'modified-roll' : ''}}">
        d{{ trait.dice }}
        {% set delta = trait.modifier + bonus %}
        {% if delta > 0 %}
            + {{ delta }}
        {% endif %}
        {% if delta < 0 %}
            - {{ -delta }}
        {% endif %}
    </button>
{% endmacro %}

{% macro print_damage(damage) %}
    <button class="pure-button" x-on:click="$dispatch('damage', {{ damage|json_encode() }} )">
        {{ damage }}
    </button>
    <button class="pure-button" x-on:click="$dispatch('damage', {{ add_raise(damage)|json_encode() }} )">
        +d6
    </button>
{% endmacro %}

{% block header_title %}
    {{ include('npc/menu.html.twig') }}
{% endblock %}

{% block info %}
    {{ parent() }}    
    <div x-data="{}">
        <h2>Lancer de trait</h2>
        <div class="diceroller" 
             x-data="traitroller" 
             x-on:roll.window="rolling($event)">
            <div x-show="dice">
                <span x-show="rateOfFire > 1" x-text="rateOfFire + '×'"></span>
                <i x-bind:class="'icon-d' + dice"></i>
                <i class="icon-d6" x-bind:class="{ 'extra-dice': !wildcard }"></i>
                <span x-show="modifier > 0" x-text="'+' + modifier"></span>
                <span x-show="modifier < 0" x-text="modifier"></span>
            </div>
            <div x-show="(dice !== null) && (result === null)" class="roll-result">
                <i class="icon-spin3 animate-spin"></i>
            </div>
            <div x-show="(dice !== null) && (result !== null)" class="roll-result">
                <template x-for="roll in result">
                    <div x-text="roll" x-bind:class="{ fumble: roll===1 }"></div>
                </template>
            </div>        
        </div>    
        <h2>Lancer de dégâts</h2>
        <div class="diceroller" 
             x-data="damageroller" 
             x-on:damage.window="rollDamage($event)">
            <div x-show="dice">
                <template x-for="(cnt,side) in dice">
                    <template x-for="i in cnt">
                        <i x-bind:class="'icon-d' + side"></i>
                    </template>
                </template>
                <span x-show="modifier > 0" x-text="'+' + modifier"></span>
            </div>
            <div x-show="(dice !== null) && (result === null)" class="roll-result">
                <i class="icon-spin3 animate-spin"></i>
            </div>
            <div x-show="(dice !== null) && (result !== null)" x-text="result" class="roll-result">
            </div>        
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="character-show" x-data="{}">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-xl-1-4">
                {% block attributes_dice %}
                    <h2>Attributs</h2>
                    <table class="pure-table">
                        {% for attr in npc.attributeRolls %}
                            <tr>
                                <td>{{ attr.label }}</td>
                                <td>{{ _self.print_trait(attr) }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endblock %}
            </div>
            <div class="pure-u-1 pure-u-xl-1-4">
                {% block skills_dice %}
                    <h2>Compétences</h2>
                    <table class="pure-table">
                        {% for skill in npc.skillRolls %}
                            <tr>
                                <td>{{ skill.label }}</td>
                                <td>{{ _self.print_trait(skill) }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endblock %}
            </div>
            <div class="pure-u-1 pure-u-xl-1-4">
                {% block abilities_list %}
                {% endblock %}
            </div>
            <div class="pure-u-1 pure-u-xl-1-4">
                {% if npc.tokenPic is not empty %}
                    <img src="{{ path('get_picture', {title: npc.tokenPic}) }}" class="pure-img"/>
                {% endif %}
                <h2>Carac. 2<sup>ndaires</sup></h2>
                <table class="pure-table">
                    <tr>
                        <td>Parade</td>
                        <td>{{ npc.parry }}</td>
                    </tr>
                    <tr>
                        <td>Malus distance</td>
                        <td>{{ npc.rangedMalus }}</td>
                    </tr>
                    <tr>
                        <td>Résistance</td>
                        <td>{{ npc.toughness }} ({{ npc.totalArmor }})</td>
                    </tr>
                    <tr>
                        <td>Sécurité</td>
                        <td>{{ npc.security }}</td>
                    </tr>
                </table>
                <h2>Armures</h2>
                <table class="pure-table">
                    {% for item in npc.armors %}
                        <tr>
                            <td>{{ item.name }}</td>
                            <td>{{ item.protect }} {{ item.special }}</td>
                            <td class="right-text">{{ item.zone }}</td>
                        </tr>
                    {% endfor %}
                    {% if npc.morph.bodyArmor > 0 %}
                        <tr>
                            <td>Morphe</td>
                            <td>{{ npc.morph.bodyArmor }}</td>
                            <td class="right-text">T/B/J/H</td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
        <div class="pure-g">
            <div class="pure-u-1">
                <h2>Attaques</h2>
                <table class="pure-table">
                    {% for item in npc.attackRolls %}
                        <tr>
                            <td>{{ item.title }}</td>
                            <td>{{ item.reach }}</td>
                            <td>{{ item.rateOfFire }}×</td>
                            <td>{{ item.roll.label }}</td>
                            <td>{{ _self.print_trait(item.roll, item.rateOfFire, item.rollBonus) }}</td>
                            <td>{{ _self.print_damage(item.damage) }}</td>
                            <td>PA {{ item.armorPiercing }}</td>                            
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }} 
    <script type="module">
        import Mousetrap from 'mousetrap';

        Mousetrap.bind('s', function () {
            location.assign('{{ path('app_npcgenerator_edit', {pk: npc.pk}) }}')
            return false
        });

        Mousetrap.bind('w', function () {
            location.assign('{{ path('app_npcgenerator_battle', {pk: npc.pk}) }}')
            return false
        });
    </script>

    <script type="module">
        import rollPool from 'dice-roller';
        import { Howl } from 'howler';

        const inceptionSound = new Howl({
            src: ['{{ asset('sound/foghorn.webm')}}', '{{ asset('sound/foghorn.ogg') }}']
        })
        const rollSound = new Howl({
            src: ['{{ asset('sound/roll.webm')}}', '{{ asset('sound/roll.ogg') }}']
        })

        Alpine.data('traitroller', () => ({
                dice: null,
                wildcard: {{ npc.wildCard ? 'true' : 'false' }},
                modifier: 0,
                result: null,
                rateOfFire: 1,
                rolling(ev) {
                    this.dice = ev.detail.dice;
                    this.modifier = ev.detail.modifier;
                    this.rateOfFire = ev.detail.rof
                    this.result = null;
                    var data = this

                    let pool = Array(this.rateOfFire).fill(this.dice)
                    pool.push(6) // wild die
                    rollPool(pool).then(function (rolled) {
                        console.log(rolled)
                        setTimeout(function () {

                            let wildDie = 0
                            if (data.wildcard) {
                                wildDie = rolled[rolled.length - 1] // keep the wild die
                                rolled.sort(function (a, b) {
                                    return b - a
                                })
                                rolled.pop() // remove the weakest value
                            } else {
                                wildDie = rolled.pop() // remove the wild die
                                rolled.sort(function (a, b) {
                                    return b - a
                                })
                            }
                            let maxi = rolled[0]

                            // sound
                            if ((maxi == 1) && (wildDie == 1)) {
                                inceptionSound.play();
                            } else {
                                rollSound.play()
                            }

                            data.result = rolled.map(function (val) {
                                return val + data.modifier
                            })
                        }, 300)
                    })
                }
            }))

        Alpine.data('damageroller', () => ({
                dice: null,
                modifier: 0,
                result: null,
                rollDamage(ev) {
                    let damage = ev.detail
                    this.dice = damage.diceCount;
                    this.modifier = damage.bonus;
                    this.result = null;
                    var data = this

                    let pool = []
                    Object.keys(damage.diceCount).forEach(function (key, index) {
                        let val = damage.diceCount[key]
                        for (let k = 0; k < val; k++) {
                            pool.push(key)
                        }
                    })
                    rollPool(pool).then(function (rolled) {
                        setTimeout(function () {
                            console.log(rolled)
                            const sum = rolled.reduce((a, b) => a + b, 0)

                            // sound
                            rollSound.play()
                            data.result = sum + data.modifier
                        }, 300)
                    })
                }
            }))
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .modified-roll {
            color: darkred;
        }
        /* the non-alignemtn of titles on the top bother me */
        .character-show .pure-u-1 > h2:first-of-type {
            margin-top: 0.3em;
        }
    </style>
{% endblock %}