src/Entity/Edge.php
<?php

/*
 * eclipse-wiki
 */

namespace App\Entity;

use JsonSerializable;
use MongoDB\BSON\Persistable;
use Trismegiste\Strangelove\MongoDb\PersistableImpl;

/**
 * An Edge
 */
class Edge extends Modifier implements Persistable, JsonSerializable
{

    use PersistableImpl;

    protected string $rank;
    protected string $category;
    protected $requis;
    public $origin = null; // creation, gift, xperience, morph, morph slot...

    public function __construct(string $str, string $rank, string $category, bool $ego = false, bool $biomorph = false, bool $synthmorph = false, $requis = '')
    {
        parent::__construct($str, $ego, $biomorph, $synthmorph);
        $this->rank = $rank;
        $this->category = $category;
        $this->requis = $requis;
    }

    public function getCategory(): string
    {
        return $this->category;
    }

    public function getRank(): string
    {
        return $this->rank;
    }

    public function getPrerequisite(): string
    {
        return $this->requis;
    }

    public function jsonSerialize(): mixed
    {
        return $this->bsonSerialize();
    }

}

src/Entity/Skill.php
<?php

/*
 * Eclipse Wiki
 */

namespace App\Entity;

use MongoDB\BSON\Persistable;
use Trismegiste\Strangelove\MongoDb\PersistableImpl;

/**
 * A SaWo Skill
 */
class Skill extends SaWoTrait implements Persistable, \JsonSerializable
{

    use PersistableImpl;

    protected string $linkedAttr;
    protected bool $core;

    public function __construct(string $str, string $linkAttr, bool $core = false)
    {
        parent::__construct($str);
        $this->linkedAttr = $linkAttr;
        $this->core = $core;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'name' => $this->name,
            'dice' => $this->dice,
            'modifier' => $this->modifier
        ];
    }

    public function getLinkedAttribute(): string
    {
        return $this->linkedAttr;
    }

    public function isCore(): bool
    {
        return $this->core;
    }

}

src/Controller/Dump.php
<?php

/*
 * eclipse-wiki
 */

namespace App\Controller;

use App\Repository\EdgeProvider;
use App\Repository\HindranceProvider;
use App\Repository\SkillProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Dump table for importing in other software
 */
class Dump extends AbstractController
{

    /**
     * Dumps all edges
     */
    #[Route('/dump/edge', methods: ['GET'])]
    public function edge(EdgeProvider $repo)
    {
        $listing = $repo->getListing();

        return $this->render('dump/edge.html.twig', ['listing' => $listing]);
    }

    /**
     * Dumps all skills
     */
    #[Route('/dump/skill', methods: ['GET'])]
    public function skill(SkillProvider $repo)
    {
        $listing = $repo->getListing();

        return $this->render('dump/skill.html.twig', ['listing' => $listing]);
    }

    /**
     * Dumps all hindrances
     */
    #[Route('/dump/hindrance', methods: ['GET'])]
    public function hindrance(HindranceProvider $repo)
    {
        $listing = $repo->getListing();

        return $this->render('dump/hindrance.html.twig', ['listing' => $listing]);
    }

    /**
     * Dumps all gears
     */
    #[Route('/dump/gear', methods: ['GET'])]
    public function gear(\App\Repository\GearProvider $repo)
    {
        $listing = $repo->getListing();

        return $this->render('dump/gear.html.twig', ['listing' => $listing]);
    }

    /**
     * Dumps all ranged weapons
     */
    #[Route('/dump/rw', methods: ['GET'])]
    public function rangedWeapon(\App\Repository\RangedWeaponProvider $repo)
    {
        $listing = $repo->getListing();

        return $this->render('dump/rangedw.html.twig', ['listing' => $listing]);
    }

}

templates/dump/edge.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <table class="pare-table pure-table-striped">
        <tr>
            <th>Categorie</th>
            <th>Nom</th>
            <th>Rang</th>
            <th>Prerequis</th>
            <th>Ego</th>
            <th>Biomorphe</th>
            <th>Synthmorphe</th>
        </tr>
        {% for edge in listing %}
            <tr>
                <td>{{ edge.category|upper }}</td>
                <td>{{ edge.name }}</td>
                <td>{{ edge.rank|upper }}</td>
                <td>{{ edge.prerequisite|replace({'[[':'',']]':''}) }}</td>
                <td>{{ edge.ego ? 'Oui' : 'Non' }}</td>
                <td>{{ edge.bio ? 'Oui' : 'Non' }}</td>
                <td>{{ edge.synth ? 'Oui' : 'Non' }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/dump/gear.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <table class="pare-table pure-table-striped">
        <tr>
            <th>Nom</th>
            <th>Prix</th>
        </tr>
        {% for gear in listing %}
            <tr>
                <td>{{ gear.name }}</td>
                <td>{{ gear.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/dump/hindrance.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <table class="pare-table pure-table-striped">
        <tr>
            <th>Nom</th>
            <th>Ego</th>
            <th>Biomorphe</th>
            <th>Synthmorphe</th>
            <th>Niveau</th>
        </tr>
        {% for hindrance in listing %}
            <tr>
                <td>{{ hindrance.name }}</td>
                <td>{{ hindrance.ego ? 'Oui' : 'Non' }}</td>
                <td>{{ hindrance.bio ? 'Oui' : 'Non' }}</td>
                <td>{{ hindrance.synth ? 'Oui' : 'Non' }}</td>
                <td>{{ level_hindrance(hindrance.choices) }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/dump/rangedw.html.twig
{# Ranged weapons dump #}
{% extends "base.html.twig" %}

{% block body %}
    <table class="pare-table pure-table-striped">
        <tr>
            <th>Nom</th>
            <th>Dégâts</th>
            <th>PA</th>
            <th>CdT</th>
            <th>Portée</th>
            <th>FOR min.</th>
            <th>Mains</th>
        </tr>
        {% for row in listing %}
            <tr>
                <td>{{ row.name }}</td>
                <td>{{ row.damage }}</td>
                <td>{{ row.ap }}</td>
                <td>{{ row.rof }}</td>
                <td>{{ row.reach }}</td>
                <td>d{{ row.minStr }}</td>
                <td>{{ row.hand }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/dump/skill.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <table class="pare-table pure-table-striped">
        <tr>
            <th>Core</th>
            <th>Nom</th>
            <th>Attribut</th>
        </tr>
        {% for skill in listing %}
            <tr>
                <td>{% if skill.core %}<i class="icon-heartbeat"></i>{% endif %}</td>
                <td>{{ skill.name }}</td>
                <td>{{ skill.linkedAttribute|upper }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}