src/Entity/Place.php
<?php

/*
 * eclipse-wiki
 */

namespace App\Entity;

use App\Attribute\PlaceIcon;

/**
 * Stage scene
 */
#[PlaceIcon('place')]
class Place extends Vertex
{

    public $world;
    public $temperature;
    public $pressure;
    public $gravity;
    public ?string $youtubeUrl = null;
    public ?string $battlemap3d = null;
    public ?MapConfig $voronoiParam = null;

    /**
     * Gets all legends (spot on battlemap) in the content
     * @return array array of LegendSpot
     */
    public function extractLegendSpot(): array
    {
        if (is_null($this->content)) {
            return [];
        }

        $matches = [];
        preg_match_all('#\{\{legend\s*\|\s*([^\|]+)\s*\|\s*(\d+)\s*\}\}#', $this->getContent(), $matches, PREG_SET_ORDER, 0);
        $spot = [];
        foreach ($matches as $item) {
            $spot[] = new LegendSpot(trim($item[1]), $item[2]);
        }

        return $spot;
    }

}

src/Form/PlaceType.php
<?php

/*
 * Eclipse Wiki
 */

namespace App\Form;

use App\Entity\Place;
use App\Form\Type\FullTextChoice;
use App\Form\Type\RandomNameType;
use App\Form\Type\YoutubeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form for creating and editing a Place
 */
class PlaceType extends AbstractType
{

    use FormTypeUtils;

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if ($options['method'] !== 'PUT') {
            $builder->add('title', RandomNameType::class, ['priority' => 1000]);
        }

        $builder
                ->add('world', FullTextChoice::class, ['category' => 'world', 'priority' => 500])
                ->add('gravity', FullTextChoice::class, ['category' => 'gravity', 'priority' => 500])
                ->add('temperature', FullTextChoice::class, ['category' => 'temperature', 'priority' => 500])
                ->add('pressure', FullTextChoice::class, ['category' => 'pressure', 'priority' => 500])
                ->add('youtubeUrl', YoutubeType::class, [
                    'required' => false,
                    'label' => 'Youtube ID',
                    'attr' => [
                        'class' => 'pure-input-1-2',
                        'placeholder' => 'ID unique de Youtube ou url de la vidéo'
                    ],
                    'priority' => 500
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Place::class,
            'empty_data' => function (FormInterface $form) {
                return new Place($form->get('title')->getData());
            }
        ]);
    }

    public function getParent(): ?string
    {
        return VertexType::class;
    }

    public function finishView(FormView $view, FormInterface $form, array $options): void
    {
        $this->changeAttribute($view, 'content', 'rows', 24);
    }

}

templates/place/actions.html.twig
{# default actions #}
<a href="{{ path('app_vertexcrud_show', {pk: vertex.pk}) }}" title="Voir"><i class="icon-eye"></i></a>
<a href="{{ path('app_placecrud_edit', {pk: vertex.pk}) }}" title="Modifier"><i class="icon-edit"></i></a>
<a href="{{ path('app_placecrud_child', {pk: vertex.pk}) }}" title="Créer un décor enfant de ce vertex"><i class="icon-newchild"></i></a>
<a href="{{ path('app_voronoicrud_edit', {pk: vertex.pk}) }}" title="Modifier la battlemap"><i class="icon-hexagon"></i></a>
    {% if vertex.voronoiParam is not empty %}
    <a href="{{ path('app_voronoicrud_texture', {pk: vertex.pk}) }}" title="Colorier la battlemap"><i class="icon-paintbrush"></i></a>
    <a href="{{ path('app_voronoicrud_populate', {pk: vertex.pk}) }}" title="Peupler la battlemap"><i class="icon-extra"></i></a>
    <a href="{{ path('app_voronoicrud_statistics', {pk: vertex.pk}) }}" title="Statistiques de la battlemap"><i class="icon-info-circled"></i></a>
    <a href="{{ path('app_firstperson_edit', {pk: vertex.pk}) }}" target="_blank" title="Explorer la Battlemap en 3D"><i class="icon-view3d"></i></a>
    {% endif %}
<a href="{{ path('app_vertexcrud_rename', {pk: vertex.pk}) }}" title="Renommer"><i class="icon-rename"></i></a>
<a href="{{ path('app_vertexcrud_delete', {pk: vertex.pk}) }}" title="Effacer"><i class="icon-trash-empty"></i></a>

templates/place/create.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'un Décor{% endblock %}

{% block header_title %}Création d'un Décor{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

templates/place/edit.html.twig
{% extends "base.html.twig" %}
{% form_theme form _self %}

{% block title %}{{ form.vars.data.title }}{% endblock %}

{% block header_title %}
    {# the header menu with title #}
    <nav style="float: right">
        {{ include('place/actions.html.twig', {vertex:form.vars.data}) }}
    </nav>   
    {% block header_big_title %}{{ form.vars.data.title }}{% endblock %}
{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

{% block _place_content_label %}
    {{ form_label(form) }}
    {% include 'fragment/form_minitoolbar.html.twig' %}
    {% set vertex = form.parent.vars.data %}
    <div class="minitoolbar" x-data="placeToolbar('{{ form.vars.id }}')">
        <a href="{{ path('app_placecrud_appendmorphbank', {pk: vertex.pk}) }}"
           class="pure-button button-delete" title="Cancel edition and append a morph bank">
            <i class="icon-cryo-morph"></i>
        </a>
        <a href="{{ path('app_ollama_contentgenerate', {pk: vertex.pk, promptKey: 'bar', prefill:{title: vertex.title}}) }}"
           class="pure-button button-delete" title="Cancel edition and append a LLM-generated description of a bar">
            <i class="icon-llm-bar"></i>
        </a>
        <a href="#" class="pure-button" title="Transform selected text into parameters" x-on:click.prevent="selectionToParam">
            <i class="icon-gear"></i>
        </a>     
    </div>
    <script type="module">
        Alpine.data('placeToolbar', (widgetId) => ({
                selectionToParam() {
                    const widget = document.getElementById(widgetId)
                    let selection = widget.value.substring(widget.selectionStart, widget.selectionEnd)
                    widget.value = widget.value.substring(0, widget.selectionStart)
                            + `<param>\n${selection}\n</param>`
                            + widget.value.substr(widget.selectionEnd)
                }
            }))
    </script>
{% endblock %}

templates/place/map_generate.html.twig
{% extends "base.html.twig" %}

{% block title %}Map{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        let onTheFly = document.querySelector('form[name=one_block_map]')

        onTheFly.addEventListener('change', function (e) {
            let data = new FormData(onTheFly)
            fetch(onTheFly.action, {
                method: 'post',
                body: data,
                redirect: 'manual'
            }).then(function (response) {
                return response.text()
            }).then(function (svg) {
                document.getElementById('map').innerHTML = svg
            }).catch((error) => {
                console.error(error);
            })
        })

        document.getElementById('map').addEventListener('click', function (e) {
            console.log(e.target.parentNode.dataset.level)
            // @todo need mar check
            document.querySelector('g[data-level="' + e.target.parentNode.dataset.level + '"]').style = 'opacity:0%'
        })
    </script>
{% endblock %}

{% block content %}
    <div class="pure-g">
        <div class="pure-u-1-5">{{ form(form) }}</div>
        <div class="pure-u-4-5" id="map"></div>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        #map {
            text-align: center;
        }
        #map svg {
            border: 1px solid black;
        }
    </style>
{% endblock %}

templates/place/morph_bank.html.twig
{# append a morph inventory #}
{% extends "place/edit.html.twig" %}

{% block content %}
    {{ form_start(form) }}
    <fieldset>
        {{ form_row(form.title) }}
        <div class="pure-g">
            <div class="pure-u-2-5">
                <h2>Listing</h2>
                {{ form_widget(form.morph_list) }}
            </div>
            <div class="pure-u-3-5">
                {{ form_widget(form.inventory) }}
            </div>
        </div>
    </fieldset>
    {{ form_end(form) }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        main .pure-form h2, main .pure-form h3 {
            margin-top: 0;
        }
    </style>
{% endblock %}

templates/place/npc_generate.html.twig
{% extends "base.html.twig" %}

{% block title %}PNJ pour {{ place.title }}{% endblock %}

{% block header_title %}
    {# the header menu with title #}
    <nav style="float: right">
        {{ include('place/actions.html.twig', {vertex:place}) }}
    </nav>   
    {% block header_big_title %}PNJ pour {{ place.title }}{% endblock %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('multiavatar/multiavatar.min.js') }}"></script>
    <script>
        var onTheFly = document.querySelector('form[name=profile_on_the_fly]')
        var avatarSample = document.querySelectorAll('[data-avatar]')

        for (const sample of avatarSample) {
            sample.innerHTML = multiavatar(sample.dataset.avatar)
            // event for sending an avatar
            sample.addEventListener("click", function (e) {
                document.getElementById('profile_on_the_fly_svg').value = this.innerHTML
                document.getElementById('profile_on_the_fly_name').value = this.dataset.avatar

                let data = new FormData(onTheFly)
                fetch(onTheFly.action, {
                    method: 'post',
                    body: data,
                    redirect: 'manual'
                }).then(function (response) {
                    return response.json()
                }).then(function (json) {
                    pushFlash(onTheFly, json.level, json.message)
                })
            })
        }
    </script>
{% endblock %}

{% block content %}
    {{ form(form,{attr: {hidden:true}}) }}
    {% for label, gender in listing %}
        <section class="pure-g quick-npc">
            {% for name in gender %}
                <div class="pure-u-1-8">
                    <figure data-avatar="{{ name }}"></figure>
                    <a href="{{ path('app_npcgenerator_create', {title: name}) }}">{{ name }}</a>
                </div>
            {% endfor %}
        </section>
    {% endfor %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .quick-npc {
            text-align: center;
        }
        .quick-npc svg {
            cursor: pointer;
        }
        .quick-npc *[data-avatar] + a {
            padding-bottom: 1em;
            display: block;
        }
    </style>
{% endblock %}

templates/place/random_npc.html.twig
{% extends "base.html.twig" %}

{% block title %}PNJ pour {{ place.title }}{% endblock %}

{% block header_title %}
    {# the header menu with title #}
    <nav style="float: right">
        {{ include('place/actions.html.twig', {vertex:place}) }}
    </nav>   
    {% block header_big_title %}PNJ pour {{ place.title }}{% endblock %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('multiavatar/multiavatar.min.js') }}"></script>
    <script>
        var onTheFly = document.querySelector('form[name=profile_on_the_fly]')
        var avatarSample = document.querySelectorAll('[data-avatar]')

        for (const sample of avatarSample) {
            sample.innerHTML = multiavatar(sample.dataset.avatar)
            // event for sending an avatar
            sample.addEventListener("click", function (e) {
                document.getElementById('profile_on_the_fly_svg').value = this.innerHTML
                document.getElementById('profile_on_the_fly_name').value = this.dataset.avatar

                let data = new FormData(onTheFly)
                fetch(onTheFly.action, {
                    method: 'post',
                    body: data,
                    redirect: 'manual'
                }).then(function (response) {
                    return response.json()
                }).then(function (json) {
                    pushFlash(onTheFly, json.level, json.message)
                })
            })
        }
    </script>
{% endblock %}

{% block content %}
    {{ form(form,{attr: {hidden:true}}) }}
    {% for label, gender in listing %}
        <section class="pure-g quick-npc">
            {% for name in gender %}
                <div class="pure-u-1-8">
                    <figure data-avatar="{{ name }}"></figure>
                    <a href="{{ path('app_placecrud_createwildcard', {title: name, template: place.npcTemplate}) }}"><i class="icon-wildcard"></i>{{ name }}</a>
                </div>
            {% endfor %}
        </section>
    {% endfor %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .quick-npc {
            text-align: center;
        }
        .quick-npc svg {
            cursor: pointer;
        }
        .quick-npc *[data-avatar] + a {
            padding-bottom: 1em;
            display: block;
        }
    </style>
{% endblock %}

templates/place/row.html.twig
<div class="pure-g">
    <div class="pure-u-1-4 pure-u-xl-1-12 thumb">
        <i class="{{ vertex_icon(item) }}"></i>
    </div>
    <div class="pure-u-3-4 pure-u-xl-1-2">
        <a href="{{ path('app_vertexcrud_show', {pk: item.pk}) }}" class="block-link">
            <h2>{{ item.title }}</h2>
            <span>Lieu :
                {{ item.gravity }},
                {{ item.pressure }},
                {{ item.temperature }}.
            </span>
        </a>
    </div>
    <div class="pure-u-1 pure-u-xl-5-12">
        <nav class="listing-action">
            {{ include('place/actions.html.twig', {vertex:item}) }}
        </nav>
    </div>
</div>

templates/place/show.html.twig
{% extends "vertex/show.html.twig" %}

{% block header_title %}
    <nav style="float: right">
        {{ include('place/actions.html.twig') }}
    </nav>
    {{ vertex.title }}
{% endblock %}

{% block content %}
    <div class="pure-g">
        <div class="pure-u-1 pure-u-xl-3-4">
            {{ parent() }}
            {% if vertex.voronoiParam is not empty and vertex.voronoiParam.tilePopulation is not empty %}
                <h2>PNJ</h2>
                Ce lieu est peuplé par :
                <ul>
                    {% for cfg in vertex.voronoiParam.tilePopulation %}
                        <li>
                            <a href="{{ path('app_placecrud_npcshow', {title: cfg.npc.label}) }}">
                                <i class="icon-user-plus"></i>
                                {{ cfg.npc.label }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <aside class="pure-u-1 pure-u-xl-1-4">
            <div class="infobox">
                <div class="conditions"><i class="icon-gravity"></i>{{ vertex.gravity }}</div>
                <div class="conditions"><i class="icon-pressure"></i>{{ vertex.pressure }}</div>
                <div class="conditions"><i class="icon-temperature"></i>{{ vertex.temperature }}</div>
                    {% if vertex.youtubeUrl is not empty %}
                    <iframe width="100%" height="150" src="https://www.youtube.com/embed/{{ vertex.youtubeUrl }}"
                            title="{{ vertex.title }}"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen>
                    </iframe>
                {% endif %}
                {{ render(controller('App\\Controller\\PlaceCrud::connectionToPlace', {place: vertex})) }}
                {% if vertex.battlemap3d is not empty %}
                    <a href="{{ path('app_firstperson_edit', {pk: vertex.pk}) }}" target="_blank">
                        <img src="{{ path('app_picture_battlemapthumbnail', {pk: vertex.pk}) }}" class="pure-img"/>
                    </a>
                {% endif %}
            </div>
        </aside>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .infobox {
            display: grid;
            gap: 1.5rem;
            grid-template-columns: 1fr;
        }
        .conditions {
            font-size: 140%;
            text-align: center;
        }
        .conditions i {
            display: block;
            font-size: 170%;
            margin-bottom: 0.2rem;
        }
        ul.place-connections {
            background-color: #eee;
            list-style-type: none;
            line-height: 160%;
            margin: 0;
            padding: 0.5em;
        }
    </style>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ include('fragment/legend_highlight.html.twig') }}
    <script type="module">
        Alpine.data('pushableContent', () => ({
                urlPush: '{{ path('app_placecrud_pushmorphbank', {pk: vertex.pk}) }}',

                pushPdf(title) {
                    fetch(this.urlPush, {method: 'POST', body: new URLSearchParams({title})})
                            .then(resp => resp.json())
                            .then(json => {
                                Alpine.store('notif').push(json.level, json.message)
                            })
                }
            }))
    </script>
{% endblock %}